######################################################
# Hecho por Minelatino Network: play.minelatino.com  #
# discord.minelatino.com   | Gasthi#1111             #
######################################################

# 1 = medio corazon
# 2 = 1 corazon
# 3 = 1 corazon y medio
# etc..

pearl-damage: 0
pearl-cooldown: 2